/*
 * generated by Xtext
 */
package net.winklerweb.cdoxtext.example;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GraphixRuntimeModule extends net.winklerweb.cdoxtext.example.AbstractGraphixRuntimeModule {

}
