/*
* generated by Xtext
*/
package net.winklerweb.cdoxtext.example;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GraphixStandaloneSetup extends GraphixStandaloneSetupGenerated{

	public static void doSetup() {
		new GraphixStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

