/*
 * generated by Xtext
 */
package net.winklerweb.cdoxtext.example.ui.contentassist

import net.winklerweb.cdoxtext.example.ui.contentassist.AbstractGraphixProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GraphixProposalProvider extends AbstractGraphixProposalProvider {
}
