/*
 * generated by Xtext
 */
package net.winklerweb.cdoxtext.example.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GraphixUiModule extends net.winklerweb.cdoxtext.example.ui.AbstractGraphixUiModule {
	public GraphixUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
