/*
* generated by Xtext
*/
package net.winklerweb.cdoxtext.example;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GraphixUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return net.winklerweb.cdoxtext.example.ui.internal.GraphixActivator.getInstance().getInjector("net.winklerweb.cdoxtext.example.Graphix");
	}
	
}
