/*
* generated by Xtext
*/
package net.winklerweb.cdoxtext.example.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import net.winklerweb.cdoxtext.example.services.GraphixGrammarAccess;

public class GraphixParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GraphixGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected net.winklerweb.cdoxtext.example.parser.antlr.internal.InternalGraphixParser createParser(XtextTokenStream stream) {
		return new net.winklerweb.cdoxtext.example.parser.antlr.internal.InternalGraphixParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "GraphixCanvas";
	}
	
	public GraphixGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GraphixGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
